version: "3.8"

services:
  avatar_db:
    container_name: avatar_db
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - avatar_db_vol:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avatar
    restart: always

  aratar_service:
    container_name: avatar_service
    image: alexseipopov/avatar_service:latest
    ports:
      - "1212:1212"
    volumes:
      - ./config/config-docker.yaml:/app/config/config.yaml


volumes:
  avatar_db_vol: